{"uuid":"617cfd51-8927-454f-8430-a7aa09987de4","name":"Scenario Outline: User validates error message for Arrays In Python in try editor page for invalid code","children":["11a85fe6-d54f-4c1e-8098-55ab3b1c5203"],"befores":[],"afters":[{"name":"hooks.Hooks.afterStep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696000351991,"stop":1696000351991},{"name":"hooks.Hooks.afterStep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696000352302,"stop":1696000352302},{"name":"hooks.Hooks.afterStep(io.cucumber.java.Scenario)","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1696000352307,"stop":1696000352307}],"start":1696000351381,"stop":1696000352307}